version: '3'
services:
  authentication:
    image: sajadkh/doctor_system_authentication
    ports:
        - 8000:8000

  doctor:
    image: sajadkh/doctor_system_doctor_panel
    ports:
        - 8001:8001
    
  patient:
    image: sajadkh/doctor_system_patient_panel
    ports:
        - 8002:8002